import "@/styles/globals.css";
import { Darker_Grotesque } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "@/trpc/react";
import Header from "./_components/ui/header";
import Footer from "./_components/ui/footer";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const darkerGrotesque = Darker_Grotesque({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={darkerGrotesque.className}>
        <Header />
        <div className="h-16" />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Footer />
      </body>
    </html>
  );
}
